### PR TITLE
Updated BGP AF module for PIP IP feature

### PR DESCRIPTION
**Pull request by stalabi1**
##### SUMMARY

BGP AF module needed to be updated with advertise-pip, advertise-pip-ip, advertise-pip-peer-ip, and advertise-svi-ip attributes for PIP IP feature

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

sonic_bgp_af

##### ADDITIONAL INFORMATION

[bgp_af_regression_report.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/8051752/bgp_af_regression_report.pdf)
[show_running_configuration_bgp_output.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/8050561/show_running_configuration_bgp_output.txt)
[show_running_configuration_bgp_output2.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/8051754/show_running_configuration_bgp_output2.txt)

### CODE REVIEW

**Comment by kerry-meyer** [comment]
Please verify that execution of the playbook operations to add (merge) each of these new attributes causes the expected corresponding additions/changes to the CLI "show running-configuration" output and add an enclosure to this PR containing the "show running-configuration" output.

**Comment by stalabi1** [comment]
@kerry-meyer Added 'show running-configuration bgp' output.

**Comment by kerry-meyer** [comment]
Thanks for posting the "show running-configuration bgp' output.

There is one additional case that should be verified: 

If the bool "advertise-pip" value is set to "true" with no local or peer IP address configured, the corresponding CLI output should reflect this:

For example:

sonic(config-router-bgp-af)# do show running-configuration bgp 
!
router bgp 30
 log-neighbor-changes
 timers 60 180
 !
 address-family l2vpn evpn
  advertise-pip                                 <<<<<<<<<
  
  If either of the IP addresses is configured (local or peer), only that configuration will be displayed, and the value of the "advertise-pip" bool configuration is not displayed.
  
Please execute and post the "show running-configuration" result for an additional test to verify that the "advertise-pip" configuration displays as expected after executing the change via an Ansible playbook to set this bool without also setting a value for either of the IP addresses.

**Comment by kerry-meyer** [comment]
Please also consider the comment that I have posted inline for the "plugins/module_utils/network/sonic/config/bgp_af/bgp_af.py" file to reduce repeated code for the "get_delete_<attribute>_request" functions.

It looks like all of the functions in the group from " get_delete_advertise_pip_request" through "get_delete_advertise_all_vni_request", with the exception of "get_delete_dampening_request", could be eliminated through the use of one common function.

**Review by kerry-meyer — APPROVED** [review]
The additional changes and UT verification look good. Thank you for providing these.

Approved.

**Pull request merged**
