### PR TITLE
Template for Pull Request

### PR DESCRIPTION
**Pull request by kannankvs**
This is PR is an extension of [PR#121](https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/121) and [PR#139](https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/139). We have added all the comments from PR121 to this PR and have commented it below. This new PR has been closed due deletion of old head repositories.

<strong>Kerry</strong> Thanks for creating these guideline. I have posted some minor comments/questions inline.

<strong>Kerry</strong> In the PR description, please provide any relevant details on recommended procedures and/or tools for measuring code coverage (if any).
<strong>KVSK</strong> We have commented the below statement under additional information section to handle this code coverage measurement. "Measure the code coverage before and after the change by running the UT and ensure that the "coverage after the change" is not less than the coverage "before the change". Note that the unit testing coverage can be manually executed using the pytest tool or ansible-test tool."

<strong>Kerry</strong> Please change this to:
I have maintained backward compatibility or have provided any relevant "breaking_changes" descriptions in a "fragment" file in the "changelogs/fragments" directory of this repository.
<strong>KVSK</strong> Addressed as suggested.

<strong>Kerry</strong> What does "vetting" mean in this requirement? Is there a recommended procedure to check for "security issues" (or is this a judgement call for the PR submitter)?
<strong>KVSK</strong> Have requested the technical team to comment on this.

<strong>Kerry</strong> Please add an item for documentation requirements: I have provided a summary for this PR in valid "fragment" file format in the "changelogs/fragments" directory of this repository branch. (REF: "https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to")
<strong>KVSK</strong> Addressed as suggested.

<strong>Kerry</strong> Please add a sentence here:
If no Github issues are affected, please indicate this with "N/A".
<strong>KVSK</strong> Addressed as suggested.

### CODE REVIEW

**Review by stalabi1 — APPROVED** [review]

**Comment by kannankvs** [comment]
There is an open item that was given as comment:
<<Kerry>> What does "vetting" mean in this requirement? Is there a recommended procedure to check for "security issues" (or is this a judgement call for the PR submitter)?
<<KVSK>> Have requested the technical team to comment on this.

**Review by kerry-meyer — APPROVED** [review]
Thank you for providing this template.

The current version looks good for merging.

Approved.

**Comment by kerry-meyer** [comment]
I have re-run the sanity tests for this PR, but they all have failed at the "build" stage. The file to be merged for this PR is based at a version of the repo that fails all sanity tests because of some missing prerequisites.

It would be better to have passing sanity tests before merging the PR.

Please sync your fork and this branch to the current main branch for the collection. When you push the merged updates to your PR branch, it should trigger a new sanity run that will pass.

**Comment by kannankvs** [comment]
> I have re-run the sanity tests for this PR, but they all have failed at the "build" stage. The file to be merged for this PR is based at a version of the repo that fails all sanity tests because of some missing prerequisites.
> 
> It would be better to have passing sanity tests before merging the PR.
> 
> Please sync your fork and this branch to the current main branch for the collection. When you push the merged updates to your PR branch, it should trigger a new sanity run that will pass.

@kerry-meyer  We synced this branch with the current main branch. Even after that we see failure. This seems to be due to recent merge for [PR#180](https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/180). Request you to wait until the issue is fixed and then rerun the jobs for this PR.

**Comment by kannankvs** [comment]
> > I have re-run the sanity tests for this PR, but they all have failed at the "build" stage. The file to be merged for this PR is based at a version of the repo that fails all sanity tests because of some missing prerequisites.
> > It would be better to have passing sanity tests before merging the PR.
> > Please sync your fork and this branch to the current main branch for the collection. When you push the merged updates to your PR branch, it should trigger a new sanity run that will pass.
> 
> @kerry-meyer We synced this branch with the current main branch. Even after that we see failure. This seems to be due to recent merge for [PR#180](https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/180). Request you to wait until the issue is fixed and then rerun the jobs for this PR.

@kerry-meyer : Issue in MAIN branch got fix. Synced this branch now. All checks are passing now. Kindly merge this.

**Review by kerry-meyer — APPROVED** [review]
Thanks for re-synching the PR branch to a stable base.

I see that all sanity and UT checks are passing now.

Re-approved.

**Pull request merged**
