### PR TITLE
lag_interfaces unit testing code added

### PR DESCRIPTION
**Pull request by kannankvs**
##### SUMMARY
Unit testing code for lag_interfaces module added

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
lag_interfaces Unit Testing

### CODE REVIEW

**Comment by kannankvs** [comment]
'replaced' and 'overridden' features are getting modified in lag_interfaces module as given in [PR196](https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/196). This UT PR can be merged once if the PR196 is merged. If this UT requires rework after merging PR196, it will be taken up after merging PR196.

**Comment by kannankvs** [comment]
Changes related to "replaced" and "overridden" in plugins directory are not required and hence removed them now. They should be synced from PR196.

**Comment by kerry-meyer** [comment]
The coverage tests are failing. Please delete the failing sections. (The current "replaced" and "overridden" implementation in the lag_interfaces module is incorrect and is not worth testing yet. The corresponding tests should be revised when the real functionality is available.)

**Comment by kannankvs** [comment]
> The coverage tests are failing. Please delete the failing sections. (The current "replaced" and "overridden" implementation in the lag_interfaces module is incorrect and is not worth testing yet. The corresponding tests should be revised when the real functionality is available.)

@kerry-meyer : I removed code for testing replaced and overridden. When I remove UT for replaced and overridden, the coverage percentage decreases below 70. Hence, I added few new combinations and improved the coverage above 70% now. Please review and merge.

**Review by kerry-meyer — APPROVED** [review]

**Pull request merged**
