### PR TITLE
Ut ntp

### PR DESCRIPTION
**Pull request by kannankvs**
##### SUMMARY
Unit testing code for NTP module added

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
NTP module Unit testing

### CODE REVIEW

**Comment by kannankvs** [comment]
This code has got dependency on the [Issue205](https://github.com/ansible-collections/dellemc.enterprise_sonic/issues/205). That issue need to be fixed for this UT to succeed.

**Comment by kerry-meyer** [comment]
The NTP bug has been fixed by https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/224. Please update your fork and this PR branch to incorporate the fix so that this PR can be approved and merged.

**Comment by kannankvs** [comment]
> The NTP bug has been fixed by #224. Please update your fork and this PR branch to incorporate the fix so that this PR can be approved and merged.

Thanks for fixing the bug. I did SYNC from main branch. All test cases are passing now. Kindly review and merge the PR.

**Review by kerry-meyer — CHANGES_REQUESTED** [review]
If a "delete_all" case or a "replaced" case is added to this test suite, that will probably exercise enough of the code to get the coverage over the 70% target.

**Review by kerry-meyer — APPROVED** [review]
Thanks for adding the additional checking.

Approved.

**Pull request merged**
