### PR TITLE
Testing against 2.11

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY

https://github.com/ansible-collections/overview/issues/45#issuecomment-813821100

### CODE REVIEW

**Comment by Andersson007** [comment]
@javeedf hi, could you please do the same for the other dell collections?

**Comment by Andersson007** [comment]
could you please fix
```
ERROR: plugins/modules/sonic_radius_server.py:0:0: no-log-needed: Argument 'key' in argument_spec could be a secret, though doesn't have `no_log` set found in config
Running sanity test 'yamllint' with Python 3.6
ERROR: plugins/modules/sonic_radius_server.py:0:0: no-log-needed: Argument 'key' in argument_spec could be a secret, though doesn't have `no_log` set found in config -> servers -> host
ERROR: plugins/modules/sonic_tacacs_server.py:0:0: no-log-needed: Argument 'key' in argument_spec could be a secret, though doesn't have `no_log` set found in config
ERROR: plugins/modules/sonic_tacacs_server.py:0:0: no-log-needed: Argument 'key' in argument_spec could be a secret, though doesn't have `no_log` set found in config -> servers -> host
ERROR: plugins/modules/sonic_users.py:0:0: no-log-needed: Argument 'password' in argument_spec could be a secret, though doesn't have `no_log` set found in config
```
See https://github.com/ansible-collections/overview/issues/45#issuecomment-798891436

Then relaunch the tests here

**Comment by javeedf** [comment]
> @javeedf hi, could you please do the same for the other dell collections?

Sure @Andersson007

**Comment by javeedf** [comment]
@Andersson007 we are getting the below error on sanity test against devel branch,

ERROR: Found 1 action-plugin-docs issue(s) which need to be resolved:
See documentation for help: https://docs.ansible.com/ansible/devel/dev_guide/testing/sanity/action-plugin-docs.html
**ERROR: plugins/action/sonic.py:0:0: action plugin has no matching module to provide documentation**

we have added as part of ignore-2.10.txt and ignore-2.11.txt.

**plugins/action/sonic.py action-plugin-docs**

We are not sure how to add as part of ignore.txt for **devel** branch. please suggest as solution

**Comment by Andersson007** [comment]
@javeedf tests/sanity/ignore-2.12.txt is used for testing against `devel` which I'm adding in this PR and it seems to contain this line

**Comment by javeedf** [comment]
Taken care in other PR. hence closing

**Comment by Andersson007** [comment]
@javeedf could you please link the mentioned PR to https://github.com/ansible-collections/overview/issues/45#issuecomment-813821100 ?

**Comment by javeedf** [comment]
> @javeedf could you please link the mentioned PR to [ansible-collections/overview#45 (comment)](https://github.com/ansible-collections/overview/issues/45#issuecomment-813821100) ?

Added, https://github.com/ansible-collections/overview/issues/45#issuecomment-822237682

**Comment by Andersson007** [comment]
thanks

**Pull request closed without merging**
